# Data Understanding

## 1. Collect initial data

Data source: https://www.kaggle.com/datasets/sturarods/anac-national-civil-aviation-agency-2000-2025?select=anac_brazil.csv

## 2. Describe data

### Main features

- Number of data sources: 1
- Format of the data: csv file
- Size of the data: 17833 MiB
- Quantity of the data:
    - number of records: 22.1M
    - number of columns: 111
- Period of the data collection: 2000-2025

### Columns description

1. **id_basica**: Numeric code identifier of the basic step in the system.
2. **id_empresa**: no description
3. **sg_empresa_icao**: ICAO acronym of the airline. It refers to the designator of the air transport company obtained from the ICAO (International Civil Aviation Organization).
4. **sg_empresa_iata**: IATA acronym of the airline. Refers to the designator of the air transport company obtained from IATA (International Air Transport Association).
5. **nm_empresa**: Name of the airline.
6. **nm_pais**: Name of the country of the nationality of the airline.
7. **ds_tipo_empresa**: Description of the type of company. It refers to the description of the type of company in relation to the service performed. It may contain the following descriptions. This variable is in disuse.
8. **nr_voo**: no description
9. **nr_singular**: Flight Singularity. It refers to the set of characters that helps in the identification of the flight, composed of letters and numbers chosen at the discretion of the airline itself.
10. **id_di**: Numerical code that references the identifier digit variable in the system.
11. **cd_di**: Identifier Digit. It refers to the character used to identify the type of authorization for each flight stage.
12. **ds_di**: Description DI. Presents the description corresponding to the Identifier Digit.
13. **ds_grupo_di**: Description of the DI group or Flight Type. Refers to the grouping of DI classifications into types of operations.
14. **dt_referencia**: Reference Date. Corresponds to the Expected Start Date of the Flight.
15. **nr_ano_referencia**: Reference Year.
16. **nr_semestre_referencia**: Reference semester number.
17. **nm_semestre_referencia**: Name of the reference semester.
18. **nr_trimestre_referencia**: Reference quarter number.
19. **nm_trimestre_referencia**: Name of the reference quarter.
20. **nr_mes_referencia**: Reference month number.
21. **nm_mes_referencia**: Name of the reference month.
22. **nr_semana_referencia**: Reference week number.
23. **nm_dia_semana_referencia**: Name of the reference week day.
24. **nr_dia_referencia**: Reference day number.
25. **nr_ano_mes_referencia**: Number representing the year and month of reference, in the format YYYYMM.
26. **id_tipo_linha**: Numerical code identifier of the line type in the system.
27. **cd_tipo_linha**: Character that identifies the type of line.
28. **ds_tipo_linha**: Description of the line type.
29. **ds_natureza_tipo_linha**: Description of the nature referring to the type of line (International/Domestic). Consider the nature of the flight, not just the stage.
30. **ds_servico_tipo_linha**: Description of the service referring to the type of line (Passenger/Cargo).
31. **ds_natureza_etapa**: Description of the nature of the flight stage (International/Domestic).
32. **hr_partida_real**: Flight departure time, calculated by the criterion of the calço and descalço.
33. **dt_partida_real**: Date of realization. It refers to the full take-off date of the stage, calculated by the criterion of the shoe and barefoot.
34. **nr_ano_partida_real**: Number of the actual departure year.
35. **nr_semestre_partida_real**: Real departure semester number.
36. **nm_semestre_partida_real**: Name of the real departure semester.
37. **nr_trimestre_partida_real**: Number of the actual departure quarter.
38. **nm_trimestre_partida_real**: Name of the actual departure quarter.
39. **nr_mes_partida_real**: Number of the real departure month.
40. **nm_mes_partida_real**: Name of the real departure month.
41. **nr_semana_partida_real**: Number of the actual departure week.
42. **nm_dia_semana_partida_real**: Name of the day of the real departure week.
43. **nr_dia_partida_real**: Number of the actual departure day.
44. **nr_ano_mes_partida_real**: Number that represents the year and the month of actual departure, in the format YYYYMM.
45. **id_aerodromo_origem**: Identifier code of the airfield of origin in the system.
46. **sg_icao_origem**: ICAO acronym of the aerodrome of origin.
47. **sg_iata_origem**: IATA acronym of the airfield of origin.
48. **nm_aerodromo_origem**: Name of the aerodrome of origin.
49. **nm_municipio_origem**: Name of the municipality of origin.
50. **sg_uf_origem**: Acronym of the Federative Unit of origin.
51. **nm_regiao_origem**: Name of the region of origin.
52. **nm_pais_origem**: Name of the country of origin.
53. **nm_continente_origem**: Name of the continent of origin.
54. **nr_etapa**: Step number. Indicates the sequence of the aerodrome of origin between the aerodromes under the same flight number.
55. **hr_chegada_real**: Flight arrival time, determined by the criteria of the calço and descalço.
56. **dt_chegada_real**: Actual date of arrival.
57. **nr_ano_chegada_real**: Number of the year of actual arrival.
58. **nr_semestre_chegada_real**: Real arrival semester number.
59. **nm_semestre_chegada_real**: Name of the real arrival semester.
60. **nr_trimestre_chegada_real**: Number of the actual arrival quarter.
61. **nm_trimestre_chegada_real**: Name of the real arrival quarter.
62. **nr_mes_chegada_real**: Number of the real month of arrival.
63. **nm_mes_chegada_real**: Name of the real month of arrival.
64. **nr_semana_chegada_real**: Number of the actual arrival week.
65. **nm_dia_semana_chegada_real**: Name of the day of the week of actual arrival.
66. **nr_dia_chegada_real**: Number of the actual day of arrival.
67. **nr_ano_mes_chegada_real**: Number that represents the year and month of actual arrival, in the format YYYYMM.
68. **id_equipamento**: Identification code of the aircraft model in the system.
69. **sg_equipamento_icao**: ICAO Designator of the aircraft model ("Type Designator").
70. **ds_modelo**: Description of the aircraft model.
71. **ds_matricula**: Aircraft registration mark.
72. **id_aerodromo_destino**: Identification code of the destination aerodrome in the system.
73. **sg_icao_destino**: ICAO acronym of the destination airfield.
74. **sg_iata_destino**: IATA acronym of the destination aerodrome.
75. **nm_aerodromo_destino**: Name of the destination aerodrome.
76. **nm_municipio_destino**: Name of the destination municipality.
77. **sg_uf_destino**: Acronym of the destination Federative Unit.
78. **nm_regiao_destino**: Name of the destination region.
79. **nm_pais_destino**: Name of the destination country.
80. **nm_continente_destino**: Name of the destination continent.
81. **nr_escala_destino**: Destination scale sequence. It is the number corresponding to the destination aerodrome of the stage, considering the sequential numbering of the aerodromes traveled under the same flight.
82. **lt_combustivel**: Amount of fuel consumed, expressed in liters.
83. **nr_assentos_ofertados**: Number of seats available at the flight stage.
84. **kg_payload**: Payload capacity, expressed in kilograms.
85. **km_distancia**: Distance, expressed in kilometers, between the aerodromes of origin and destination of the stage, considering the curvature of planet earth.
86. **nr_passag_pagos**: Number of passengers who occupy seats marketed to the public and who generate revenue, with the purchase of seats, for the air transport company.
87. **nr_passag_gratis**: Number of passengers who occupy seats marketed to the public, but do not generate revenue, with the purchase of seats, for the air transport company.
88. **kg_bagagem_livre**: Franchised baggage. It is all baggage that is not considered as excess, expressed in kilograms.
89. **kg_bagagem_excesso**: Excess baggage. It is the total amount of baggage that exceeds the weight limit agreed between the airline and the passenger, checked at the time of dispatch, expressed in kilograms.
90. **kg_carga_paga**: Cargo paid. It is the total amount, expressed in kilograms, of all goods that have been transported on the aircraft, except mail and luggage, and have generated direct or indirect revenue for the airline.
91. **kg_carga_gratis**: Total quantity, expressed in kilograms, of all goods that have been transported on the aircraft, except mail and baggage, and have not generated direct or indirect revenues for the airline.
92. **kg_correio**: Quantity, expressed in kilograms, of objects transported to serve the operators officially designated by the country to operate postal services and comply with the associated obligations arising from the Acts of the Universal Postal Union (UPU).
93. **nr_decolagem**: Number of takeoffs.
94. **nr_horas_voadas**: Number of hours flown.
95. **kg_peso**: Refers to the total weight loaded by the aircraft, calculated by the sum of cargo, mail, passengers and luggage, expressed in kg.
96. **nr_velocidade_media**: Average flight speed, calculated from the distance and duration of the flight, expressed in km/h.
97. **nr_pax_gratis_km**: Represents, for each basic step, the product between the number of free passengers and the distance of the stage.
98. **nr_carga_paga_km**: Refers to the product between the amount of load paid (kg) and the distance of the basic step (km).
99. **nr_carga_gratis_km**: Refers to the product between the amount of free load (kg) and the distance of the basic step (km).
100. **nr_correio_km**: Refers to the product between the amount of mail (kg) and the distance of the basic step (km).
101. **nr_bagagem_paga_km**: Refers to the product between the amount of baggage paid (kg) and the distance of the basic step (km).
102. **nr_bagagem_gratis_km**: Refers to the product between the amount of free baggage (kg) and the distance from the basic step (km).
103. **nr_ask**: Refers to the volume of Seat Kilometers Offered (Available Seat Kilometer). It is calculated, in each basic step, by the product between the number of seats offered and the distance of the stage.
104. **nr_rpk**: Refers to the volume of Passenger Kilometers Transported (Revenue Passenger Kilometer). It is calculated, in each basic step, by the product between the number of passengers paid and the distance of the stage.
105. **nr_atk**: Refers to the volume of Tons Kilometers Offered (Available Tonne Kilometer), expressed in (ton x km). It is calculated, in each basic step, by the product between the Payload Capacity (kg) and the distance of the step, divided by 1000.
106. **nr_rtk**: Refers to the volume of Tonnes Transported Kilometers (Revenue Tonne Kilometer), expressed in (ton x km). It is calculated, in each basic step, by the product between the quantity, expressed in kilograms, of passengers, luggage, cargo and mail paid transported and the distance of the stage, divided by 1000.
107. **id_arquivo**: Identifier code of the data file sent to the system.
108. **nm_arquivo**: File name sent to the system.
109. **nr_linha**: File line number in which the data of each basic step are contained.
110. **dt_sistema**: Date on which the information was recorded in the system.
111. **nr_chave**: no description

### Sample data

In [8]:
import pandas as pd

df = pd.read_csv('anac_brazil.csv', nrows = 100000)
pd.set_option('display.max_columns', None)
df.head()

C:\Users\kuzzm\AppData\Local\Temp\ipykernel_3496\2031630969.py:3: DtypeWarning: Columns (0: cd_di) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('anac_brazil.csv', nrows = 100000)

,id_basica,id_empresa,sg_empresa_icao,sg_empresa_iata,nm_empresa,nm_pais,ds_tipo_empresa,nr_voo,nr_singular,id_di,cd_di,ds_di,ds_grupo_di,dt_referencia,nr_ano_referencia,nr_semestre_referencia,nm_semestre_referencia,nr_trimestre_referencia,nm_trimestre_referencia,nr_mes_referencia,nm_mes_referencia,nr_semana_referencia,nm_dia_semana_referencia,nr_dia_referencia,nr_ano_mes_referencia,id_tipo_linha,cd_tipo_linha,ds_tipo_linha,ds_natureza_tipo_linha,ds_servico_tipo_linha,ds_natureza_etapa,hr_partida_real,dt_partida_real,nr_ano_partida_real,nr_semestre_partida_real,nm_semestre_partida_real,nr_trimestre_partida_real,nm_trimestre_partida_real,nr_mes_partida_real,nm_mes_partida_real,nr_semana_partida_real,nm_dia_semana_partida_real,nr_dia_partida_real,nr_ano_mes_partida_real,id_aerodromo_origem,sg_icao_origem,sg_iata_origem,nm_aerodromo_origem,nm_municipio_origem,sg_uf_origem,nm_regiao_origem,nm_pais_origem,nm_continente_origem,nr_etapa,hr_chegada_real,dt_chegada_real,nr_ano_chegada_real,nr_semestre_chegada_real,nm_semestre_chegada_real,nr_trimestre_chegada_real,nm_trimestre_chegada_real,nr_mes_chegada_real,nm_mes_chegada_real,nr_semana_chegada_real,nm_dia_semana_chegada_real,nr_dia_chegada_real,nr_ano_mes_chegada_real,id_equipamento,sg_equipamento_icao,ds_modelo,ds_matricula,id_aerodromo_destino,sg_icao_destino,sg_iata_destino,nm_aerodromo_destino,nm_municipio_destino,sg_uf_destino,nm_regiao_destino,nm_pais_destino,nm_continente_destino,nr_escala_destino,lt_combustivel,nr_assentos_ofertados,kg_payload,km_distancia,nr_passag_pagos,nr_passag_gratis,kg_bagagem_livre,kg_bagagem_excesso,kg_carga_paga,kg_carga_gratis,kg_correio,nr_decolagem,nr_horas_voadas,kg_peso,nr_velocidade_media,nr_pax_gratis_km,nr_carga_paga_km,nr_carga_gratis_km,nr_correio_km,nr_bagagem_paga_km,nr_bagagem_gratis_km,nr_ask,nr_rpk,nr_atk,nr_rtk,id_arquivo,nm_arquivo,nr_linha,dt_sistema,nr_chave
0,9705464.0,1000909,AZU,AD,AZUL LINHAS AÉREAS BRASILEIRAS S/A,BRASIL,TRANSPORTE AÉREO REGULAR,6956,242,2,0,REGULAR PREVISTO EM HOTRAN,REGULAR,2013-08-01,2013,2,2º SEMESTRE,3,3º TRIMESTRE,8,AGOSTO,31,QUINTA-FEIRA,1,201308,1,N,DOMÉSTICA MISTA,DOMÉSTICA,PASSAGEIRO,DOMÉSTICA,08:27:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,693,SBCT,CWB,AFONSO PENA,SÃO JOSÉ DOS PINHAIS,PR,SUL,BRASIL,AMÉRICA DO SUL,1,09:54:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,272,E195,EMBRAER 195,AXU,301,SBGR,GRU,GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO,GUARULHOS,SP,SUDESTE,BRASIL,AMÉRICA DO SUL,NaN,2347.0,118.0,15505.0,359.0,75.0,1.0,391.0,42.0,4.0,0.0,0.0,1,"1,45",6137.0,"247,828",359.0,1436,0.0,0.0,15078.0,140369.0,42362.0,26925.0,5566.0,2176.0,8967,AZUAGO13.txt,15843.0,2019-08-25 22:57:15,NaN
1,9705140.0,1000909,AZU,AD,AZUL LINHAS AÉREAS BRASILEIRAS S/A,BRASIL,TRANSPORTE AÉREO REGULAR,4202,372,2,0,REGULAR PREVISTO EM HOTRAN,REGULAR,2013-08-01,2013,2,2º SEMESTRE,3,3º TRIMESTRE,8,AGOSTO,31,QUINTA-FEIRA,1,201308,1,N,DOMÉSTICA MISTA,DOMÉSTICA,PASSAGEIRO,DOMÉSTICA,11:35:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,693,SBCT,CWB,AFONSO PENA,SÃO JOSÉ DOS PINHAIS,PR,SUL,BRASIL,AMÉRICA DO SUL,1,12:38:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,272,E195,EMBRAER 195,AXI,162,SBKP,VCP,VIRACOPOS,CAMPINAS,SP,SUDESTE,BRASIL,AMÉRICA DO SUL,NaN,2048.0,118.0,16254.0,349.0,60.0,2.0,457.0,68.0,495.0,0.0,0.0,1,"1,05",5670.0,"332,153",698.0,172755,0.0,0.0,23732.0,159493.0,41182.0,20940.0,5672.0,1926.0,8967,AZUAGO13.txt,44539.0,2019-08-25 22:57:15,NaN
2,9705149.0,1000909,AZU,AD,AZUL LINHAS AÉREAS BRASILEIRAS S/A,BRASIL,TRANSPORTE AÉREO REGULAR,4027,377,2,0,REGULAR PREVISTO EM HOTRAN,REGULAR,2013-08-01,2013,2,2º SEMESTRE,3,3º TRIMESTRE,8,AGOSTO,31,QUINTA-FEIRA,1,201308,1,N,DOMÉSTICA MISTA,DOMÉSTICA,PASSAGEIRO,DOMÉSTICA,22:39:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,693,SBCT,CWB,AFONSO PENA,SÃO JOSÉ DOS PINHAIS,PR,SUL,BRASIL,AMÉRICA DO SUL,1,23:50:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,271,E190,EMBRAER 190,AZA,162,SBKP,VCP,VIRACOPOS,CAMPINAS,SP,SUDESTE,BRASIL,AMÉRICA DO SUL,NaN,2059.0,106.0,15974.0,349.0,55.0,1.0,385.0,82.0,188.0,0.0,0.0,1,"1,18",4855.0,"295,56",349.0,65612,0.0,0.0,28618.0,134365.0,36994.0,19195.0,5574.0,1668.0,8967,AZUAGO13.txt,45470.0,2019-08-25 22:57:15,NaN
3,9705563.0,1000909,AZU,AD,AZUL LINHAS AÉREAS BRASILEIRAS S/A,BRASIL,TRANSPORTE AÉREO REGULAR,5050,181,2,0,REGULAR PREVISTO EM HOTRAN,REGULAR,2013-08-01,2013,2,2º SEMESTRE,3,3º TRIMESTRE,8,AGOSTO,31,QUINTA-FEIRA,1,201308,1,N,DOMÉSTICA MISTA,DOMÉSTICA,PASSAGEIRO,DOMÉSTICA,15:37:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,693,SBCT,CWB,AFONSO PENA,SÃO JOSÉ DOS PINHAIS,PR,SUL,BRASIL,AMÉRICA DO SUL,2,16:35:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,271,E190,EMBRAER 190,AZA,452,SBMG,MGF,SÍLVIO NAME JÚNIOR,MARINGÁ,PR,SUL,BRASIL,AMÉRICA DO SUL,NaN,2002.0,106.0,15624.0,367.0,55.0,1.0,495.0,19.0,30.0,0.0,0.0,1,"0,97",4744.0,"377,943",367.0,11010,0.0,0.0,6973.0,181665.0,38902.0,20185.0,5734.0,1713.0,8967,AZUAGO13.txt,6760.0,2019-08-25 22:57:15,NaN
4,9705565.0,1000909,AZU,AD,AZUL LINHAS AÉREAS BRASILEIRAS S/A,BRASIL,TRANSPORTE AÉREO REGULAR,5051,181,2,0,REGULAR PREVISTO EM HOTRAN,REGULAR,2013-08-01,2013,2,2º SEMESTRE,3,3º TRIMESTRE,8,AGOSTO,31,QUINTA-FEIRA,1,201308,1,N,DOMÉSTICA MISTA,DOMÉSTICA,PASSAGEIRO,DOMÉSTICA,18:10:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,693,SBCT,CWB,AFONSO PENA,SÃO JOSÉ DOS PINHAIS,PR,SUL,BRASIL,AMÉRICA DO SUL,2,19:31:00,2013-08-01,2013.0,2.0,2º SEMESTRE,3.0,3º TRIMESTRE,8.0,AGOSTO,31.0,QUINTA-FEIRA,1.0,201308.0,271,E190,EMBRAER 190,AZA,628,SBRJ,SDU,SANTOS DUMONT,RIO DE JANEIRO,RJ,SUDESTE,BRASIL,AMÉRICA DO SUL,NaN,2904.0,106.0,15470.0,676.0,78.0,1.0,455.0,124.0,18.0,0.0,0.0,1,"1,35",6522.0,"500,56",676.0,12168,0.0,0.0,83824.0,307580.0,71656.0,52728.0,10457.0,4358.0,8967,AZUAGO13.txt,6875.0,2019-08-25 22:57:15,NaN

### Initial inspectation: attribute types, value range, basic statistics

In [15]:
pd.set_option('display.max_info_columns', 111)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 111 columns):
 #    Column                      Non-Null Count   Dtype
---   ------                      --------------   -----
 0    id_basica                   100000 non-null  float64
 1    id_empresa                  100000 non-null  int64
 2    sg_empresa_icao             100000 non-null  str
 3    sg_empresa_iata             99548 non-null   str
 4    nm_empresa                  100000 non-null  str
 5    nm_pais                     100000 non-null  str
 6    ds_tipo_empresa             100000 non-null  str
 7    nr_voo                      100000 non-null  int64
 8    nr_singular                 100000 non-null  int64
 9    id_di                       100000 non-null  int64
 10   cd_di                       100000 non-null  object
 11   ds_di                       100000 non-null  str
 12   ds_grupo_di                 100000 non-null  str
 13   dt_referencia               100000 non-null  str
 14   nr_ano_referencia           100000 non-null  int64
 15   nr_semestre_referencia      100000 non-null  int64
 16   nm_semestre_referencia      100000 non-null  str
 17   nr_trimestre_referencia     100000 non-null  int64
 18   nm_trimestre_referencia     100000 non-null  str
 19   nr_mes_referencia           100000 non-null  int64
 20   nm_mes_referencia           100000 non-null  str
 21   nr_semana_referencia        100000 non-null  int64
 22   nm_dia_semana_referencia    100000 non-null  str
 23   nr_dia_referencia           100000 non-null  int64
 24   nr_ano_mes_referencia       100000 non-null  int64
 25   id_tipo_linha               100000 non-null  int64
 26   cd_tipo_linha               100000 non-null  str
 27   ds_tipo_linha               100000 non-null  str
 28   ds_natureza_tipo_linha      100000 non-null  str
 29   ds_servico_tipo_linha       100000 non-null  str
 30   ds_natureza_etapa           100000 non-null  str
 31   hr_partida_real             100000 non-null  str
 32   dt_partida_real             100000 non-null  str
 33   nr_ano_partida_real         100000 non-null  float64
 34   nr_semestre_partida_real    100000 non-null  float64
 35   nm_semestre_partida_real    100000 non-null  str
 36   nr_trimestre_partida_real   100000 non-null  float64
 37   nm_trimestre_partida_real   100000 non-null  str
 38   nr_mes_partida_real         100000 non-null  float64
 39   nm_mes_partida_real         100000 non-null  str
 40   nr_semana_partida_real      100000 non-null  float64
 41   nm_dia_semana_partida_real  100000 non-null  str
 42   nr_dia_partida_real         100000 non-null  float64
 43   nr_ano_mes_partida_real     100000 non-null  float64
 44   id_aerodromo_origem         100000 non-null  int64
 45   sg_icao_origem              100000 non-null  str
 46   sg_iata_origem              98143 non-null   str
 47   nm_aerodromo_origem         100000 non-null  str
 48   nm_municipio_origem         100000 non-null  str
 49   sg_uf_origem                93530 non-null   str
 50   nm_regiao_origem            93530 non-null   str
 51   nm_pais_origem              100000 non-null  str
 52   nm_continente_origem        100000 non-null  str
 53   nr_etapa                    100000 non-null  int64
 54   hr_chegada_real             100000 non-null  str
 55   dt_chegada_real             100000 non-null  str
 56   nr_ano_chegada_real         100000 non-null  float64
 57   nr_semestre_chegada_real    100000 non-null  float64
 58   nm_semestre_chegada_real    100000 non-null  str
 59   nr_trimestre_chegada_real   100000 non-null  float64
 60   nm_trimestre_chegada_real   100000 non-null  str
 61   nr_mes_chegada_real         100000 non-null  float64
 62   nm_mes_chegada_real         100000 non-null  str
 63   nr_semana_chegada_real      100000 non-null  float64
 64   nm_dia_semana_chegada_real  100000 non-null  str
 65   nr_dia_chegada_real         100000 non-null  float64
 66   nr_ano_mes_chegada_real     100000 non-null  float64
 67   id_equipamento              100000 non-null  int64
 68   sg_equipamento_icao         100000 non-null  str
 69   ds_modelo                   100000 non-null  str
 70   ds_matricula                91164 non-null   str
 71   id_aerodromo_destino        100000 non-null  int64
 72   sg_icao_destino             100000 non-null  str
 73   sg_iata_destino             98135 non-null   str
 74   nm_aerodromo_destino        100000 non-null  str
 75   nm_municipio_destino        100000 non-null  str
 76   sg_uf_destino               93534 non-null   str
 77   nm_regiao_destino           93534 non-null   str
 78   nm_pais_destino             100000 non-null  str
 79   nm_continente_destino       100000 non-null  str
 80   nr_escala_destino           0 non-null       float64
 81   lt_combustivel              91391 non-null   float64
 82   nr_assentos_ofertados       100000 non-null  float64
 83   kg_payload                  100000 non-null  float64
 84   km_distancia                99996 non-null   float64
 85   nr_passag_pagos             100000 non-null  float64
 86   nr_passag_gratis            100000 non-null  float64
 87   kg_bagagem_livre            91164 non-null   float64
 88   kg_bagagem_excesso          91164 non-null   float64
 89   kg_carga_paga               100000 non-null  float64
 90   kg_carga_gratis             100000 non-null  float64
 91   kg_correio                  100000 non-null  float64
 92   nr_decolagem                100000 non-null  int64
 93   nr_horas_voadas             100000 non-null  str
 94   kg_peso                     100000 non-null  float64
 95   nr_velocidade_media         99996 non-null   str
 96   nr_pax_gratis_km            99996 non-null   float64
 97   nr_carga_paga_km            100000 non-null  int64
 98   nr_carga_gratis_km          99996 non-null   float64
 99   nr_correio_km               100000 non-null  float64
 100  nr_bagagem_paga_km          91167 non-null   float64
 101  nr_bagagem_gratis_km        91167 non-null   float64
 102  nr_ask                      99996 non-null   float64
 103  nr_rpk                      100000 non-null  float64
 104  nr_atk                      99996 non-null   float64
 105  nr_rtk                      99996 non-null   float64
 106  id_arquivo                  100000 non-null  int64
 107  nm_arquivo                  100000 non-null  str
 108  nr_linha                    100000 non-null  float64
 109  dt_sistema                  100000 non-null  str
 110  nr_chave                    0 non-null       float64
dtypes: float64(39), int64(19), object(1), str(52)
memory usage: 137.3+ MB

In [9]:
df.describe()

,id_basica,id_empresa,nr_voo,nr_singular,id_di,nr_ano_referencia,nr_semestre_referencia,nr_trimestre_referencia,nr_mes_referencia,nr_semana_referencia,nr_dia_referencia,nr_ano_mes_referencia,id_tipo_linha,nr_ano_partida_real,nr_semestre_partida_real,nr_trimestre_partida_real,nr_mes_partida_real,nr_semana_partida_real,nr_dia_partida_real,nr_ano_mes_partida_real,id_aerodromo_origem,nr_etapa,nr_ano_chegada_real,nr_semestre_chegada_real,nr_trimestre_chegada_real,nr_mes_chegada_real,nr_semana_chegada_real,nr_dia_chegada_real,nr_ano_mes_chegada_real,id_equipamento,id_aerodromo_destino,nr_escala_destino,lt_combustivel,nr_assentos_ofertados,kg_payload,km_distancia,nr_passag_pagos,nr_passag_gratis,kg_bagagem_livre,kg_bagagem_excesso,kg_carga_paga,kg_carga_gratis,kg_correio,nr_decolagem,kg_peso,nr_pax_gratis_km,nr_carga_paga_km,nr_carga_gratis_km,nr_correio_km,nr_bagagem_paga_km,nr_bagagem_gratis_km,nr_ask,nr_rpk,nr_atk,nr_rtk,id_arquivo,nr_linha,nr_chave
count,1.000000e+05,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.00000,100000.00000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,0.0,91391.000000,100000.00000,100000.000000,99996.000000,100000.000000,100000.000000,91164.000000,91164.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,9.999600e+04,1.000000e+05,9.999600e+04,1.000000e+05,9.116700e+04,9.116700e+04,9.999600e+04,1.000000e+05,9.999600e+04,99996.000000,100000.00000,100000.000000,0.0
mean,1.059596e+07,1.000805e+06,3798.341510,312.497080,4.162770,2013.06365,1.93635,2.872700,7.554450,31.338030,15.95986,201313.919450,1.369570,2013.06365,1.936340,2.872690,7.554760,31.339650,15.963320,201313.919760,434.79001,1.274320,2013.06365,1.936340,2.872690,7.556970,31.351480,15.980640,201313.92197,104.079340,431.082750,NaN,4969.149424,142.12431,18892.736820,1329.551192,101.916010,2.027690,1150.060627,34.241170,1191.525750,8.020890,163.560490,0.997730,10238.541520,3.333293e+03,5.385593e+06,1.321876e+04,2.633688e+05,3.069337e+04,1.672444e+06,2.359156e+05,1.823788e+05,3.981175e+04,22096.358114,9116.43465,28112.558870,NaN
std,1.793138e+06,2.828136e+02,2216.571536,178.862629,4.484832,0.24413,0.24413,0.488259,1.708907,7.467733,8.93836,22.704055,1.430192,0.24413,0.244147,0.488267,1.709114,7.468135,8.937691,22.703984,231.07380,0.689937,0.24413,0.244147,0.488267,1.710118,7.470048,8.936693,22.70366,94.705105,231.471462,NaN,8053.263962,57.72777,17252.022156,1804.466487,52.551548,3.079938,931.503471,76.168358,5994.701853,78.013412,1696.688458,0.047591,7462.246092,1.198511e+04,3.516106e+07,4.525562e+05,2.463122e+06,9.709436e+04,5.508122e+06,4.784828e+05,4.018444e+05,1.165515e+05,58343.434155,247.60574,26835.703715,NaN
min,9.705115e+06,1.000002e+06,2.000000,0.000000,2.000000,2013.00000,1.00000,1.000000,1.000000,1.000000,1.00000,201308.000000,0.000000,2013.00000,1.000000,1.000000,1.000000,1.000000,1.000000,201306.000000,11.00000,1.000000,2013.00000,1.000000,1.000000,1.000000,1.000000,1.000000,201306.00000,12.000000,11.000000,NaN,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,8967.00000,1.000000,NaN
25%,9.903747e+06,1.000641e+06,1788.000000,218.000000,2.000000,2013.00000,2.00000,3.000000,8.000000,32.000000,8.00000,201308.000000,1.000000,2013.00000,2.000000,3.000000,8.000000,32.000000,8.000000,201308.000000,218.00000,1.000000,2013.00000,2.000000,3.000000,8.000000,32.000000,8.000000,201308.00000,15.000000,218.000000,NaN,2466.000000,118.00000,14356.000000,407.000000,67.000000,0.000000,549.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6211.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.378960e+05,5.194000e+04,3.093950e+04,6.407000e+03,2858.000000,8979.00000,4087.000000,NaN
50%,1.027523e+07,1.000854e+06,3720.000000,273.000000,2.000000,2013.00000,2.00000,3.000000,8.000000,33.000000,16.00000,201308.000000,1.000000,2013.00000,2.000000,3.000000,8.000000,33.000000,16.000000,201308.000000,438.00000,1.000000,2013.00000,2.000000,3.000000,8.000000,33.000000,16.000000,201308.00000,100.000000,438.000000,NaN,3543.000000,144.00000,16900.000000,741.000000,100.000000,1.000000,970.000000,0.000000,27.000000,0.000000,0.000000,1.000000,9171.000000,5.910000e+02,1.610400e+04,0.000000e+00,0.000000e+00,0.000000e+00,6.167620e+05,9.514500e+04,6.451500e+04,1.149100e+04,6236.500000,9048.00000,20406.500000,NaN
75%,1.058107e+07,1.001093e+06,5428.000000,360.000000,2.000000,2013.00000,2.00000,3.000000,8.000000,34.000000,24.00000,201308.000000,1.000000,2013.00000,2.000000,3.000000,8.000000,34.000000,24.000000,201308.000000,628.00000,1.000000,2013.00000,2.000000,3.000000,8.000000,34.000000,24.000000,201308.00000,112.000000,628.000000,NaN,5426.500000,177.00000,18500.000000,1452.000000,134.000000,3.000000,1572.000000,30.000000,499.000000,0.000000,0.000000,1.000000,12598.250000,2.290000e+03,4.273358e+05,0.000000e+00,0.000000e+00,1.467700e+04,1.560480e+06,2.013600e+05,1.536800e+05,2.338200e+04,14998.000000,9096.00000,45811.250000,NaN
max,1.829025e+07,1.001738e+06,9991.000000,999.000000,15.000000,2014.00000,2.00000,3.000000,8.000000,35.000000,31.00000,201401.000000,8.000000,2014.00000,2.000000,3.000000,9.000000,36.000000,31.000000,201401.000000,5999.00000,8.000000,2014.00000,2.000000,3.000000,9.000000,36.000000,31.000000,201402.00000,368.000000,5999.000000,NaN,126955.000000,432.00000,550000.000000,12217.000000,432.000000,175.000000,15323.000000,2039.000000,131636.000000,10016.000000,54567.000000,1.000000,131636.000000,1.681580e+06,9.743250e+08,9.448090e+07,1.433640e+08,2.820950e+06,1.094570e+08,4.324820e+06,4.263730e+06,4.534200e+06,974324.000000,9882.00000,98814.000000,NaN

### Attribute analysis

1. Attribute correlations:
    - *Time correlation:* `dt_referencia`, `nr_ano_referencia`, `nr_mes_referencia`, `nr_dia_referencia`, `nr_ano_mes_referencia`, `nr_semana_referencia`, `nr_trimestre_referencia` - these attributes encode the same date/time at different level of detalization.
    - *Distance and capacity:* `km_distancia` and `nr_ask`, `nr_rpk`, `nr_atk`, `nr_rtk` - each of these attributes scales with distance; `kg_pesoatis`, `kg_correio`, `kg_bagagem_livre`, `kg_bagagem_excesso`, `nr_passag_pagos`, `nr_passag_gratis` - total aircraft weight is built from those attributes.
    - *Passangers and load:* `nr_passag_pagos` and `nr_rpk`, `nr_passag_gratis` and `nr_pax_gratis_km`, `kg_carga_paga` and `nr_carga_paga_km`, `kg_carga_gratis` and `nr_carga_gratis_km`, `kg_correio` and `nr_correio_km`, `kg_bagagem_livre` and `nr_bagagem_gratis_km`, `kg_bagagem_excesso` and `nr_bagagem_paga_km` - these pairs of attributes are mathematically linked, since each `*_km` variable is the product of a load/passenger measure and distance.
2. Basic statistics analysis and its meaning in business terms:

The dataset contains highly heterogeneous flights. For example, `km_distancia` has standard deviation of 1800 km, which means the data includes both domestic and international flights and therefore reflects different operational contexts.

Passenger-related variables are relatively stable compared to cargo variables: `nr_passag_pagos` is centered around 100 passengers per leg, while `nr_passag_gratis` is much lower, which suggests that most traffic comes from revenue passengers. In contrast, cargo attributes such as `kg_carga_paga` and `kg_correio` are highly skewed, with many zero or small values and a few very large ones, showing that cargo transport is concentrated in a smaller number of flights.

This means that business decisions based on the dataset should not rely only on averages, because the averages hide strong differences between route types, airlines, and flight purposes.

3. Most relevant attributes according to data mining goal:
    - `id_basica`: Numeric code identifier of the basic step in the system.
    - `sg_empresa_icao`: ICAO acronym of the airline.
    - `dt_partida_real`: Date of realization.
    - `cd_di`: Character used to identify the type of authorization for each flight stage.
    - `ds_grupo_di`: Description of the DI group or Flight Type. 
    - `cd_tipo_linha`: Character that identifies the type of line.
    - `sg_icao_origem`: ICAO acronym of the aerodrome of origin.
    - `nm_municipio_origem`: Name of the municipality of origin.
    - `sg_uf_origem`: Acronym of the Federative Unit of origin.
    - `nm_pais_origem`: Name of the country of origin.
    - `nm_continente_origem`: Name of the continent of origin.
    - `sg_icao_destino`: ICAO acronym of the destination airfield.
    - `nm_municipio_destino`: Name of the destination municipality.
    - `sg_uf_destino`: Acronym of the destination Federative Unit.
    - `nm_pais_destino`: Name of the destination country.
    - `nm_continente_destino`: Name of the destination continent.
    - `km_distancia`: Distance, expressed in kilometers, between the aerodromes of origin and destination of the stage, considering the curvature of planet earth.
    - `nr_passag_pagos`: Number of passengers who occupy seats 
    - `nr_passag_gratis`: Number of passengers who occupy seats marketed to the public, but do not generate revenue, with the purchase of seats, for the air transport company.
    - `nr_rpk`: Refers to the volume of Passenger Kilometers Transported (Revenue Passenger Kilometer). It is calculated, in each basic step, by the product between the number of passengers paid and the distance of the stage.
    - `nr_ask`: Refers to the volume of Seat Kilometers Offered (Available Seat Kilometer). It is calculated, in each basic step, by the product between the number of seats offered and the distance of the stage.
    - `nr_carga_paga_km`: Refers to the product between the amount of load paid (kg) and the distance of the basic step (km).
    - `nr_carga_gratis_km`: Refers to the product between the amount of free load (kg) and the distance of the basic step (km).
    
4. Data balancing:

Data balancing is not necessary because our main task is time-series prediction, not classification.

## Explore data

## Verify data quality